version: '3'
services:
        web: 
                build: .
                command: mix phx.server
                volumes:
                        - ${PWD}/:/app:rw
                ports:
                        - "80:4000"
                depends_on:
                        - db
                links:
                        - db
        db:
                image: postgres:alpine

